export const Colors = {
    primary: '#2f80ed',
    titleText: '#050F19',
    contentText: '#333',
    secondaryContentText: '#050F19',
    validationText: '#95acca', // grey
    primaryBottomTabIconColor: '#95acca',
    backToTopButton: '#f2f2f2',
    secondaryBorderColor: '#bdbdbd',
    primarySelectorTextColor: '#000',
    primaryBackgroundColor: '#fff',
    secondaryTextColor: '#828282',
    primaryIconColor: 'rgba(51,51,51,1)',
    oz: '#B7B7B7', // did not used
    gainsColor: '#135d2d',
    losesColor: '#a01313',
    iconEyes: '#4B6487',
    primaryBorderColor: 'rgba(47, 128, 237, 0.3)',
    iconDone: '#135D2D',
    disabledPrimary: '#c1d9fa',
    error: '#EB5757',
    disabledError: '#f39a9a',
    backgroundSilver: '#B7D5FF',
    backgroundGold: '#FFEDBB',
    backgroundPlatinum: '#B9DFC9',
    backgroundPalladium: '#F8D5B5',
    titleColorGold: '#FFBD00',
    titleColorPlatinum: '#219653',
    titleColorPalladium: '#F2994A',
    paymentDivider: '#E0E7F1',
    payPal: '#F6C657',
    inStockLable: '#27AE60',
    inStockCheckMarkIcon: '#27AE60',
    positiveGreen: '#22974A',
    negativeRed: '#D9545B',
    tabBarIndicator: 'rgba(255, 255, 255, 0.3)',
    prestonRoadcontactUsScreen: '#660517',
    redirectComponentHomeScreenStartTrading: '#C1DAFA',
    redirectComponentHomeScreenAutoBuy: '#FFEBB3',
    transactionsViewMoreScreenBgColor: 'rgba(105, 105, 105, 0.8)',
    switchbackgroundActive: '#8EB7ED',
    switchbackgroundInactive: '#C8D4E5',
    totalPerformanceText: '#050F19',
    toastInfoTypeBackgroundColor: '#ECF4FD',
    toastInfoTypeBorderColor: '#B3D1F8',
    toastInfoTypeTextColor: '#2f80ed',
    bottomTabMenuButton: '#fff',
    toolTipBackground: '#fff',
    breakdownGraphicCashBalancePart: '#333333',
    buttonTextColor: '#fff',
    formTextInputBackgroundColor: '#fff',
    formTextInputColor: '#333333',
    chartLablePrimatyColor: '#696969',
    holdingTopTabBarPrimary: '#fff',
    spotPriceChangeColorDefault: '#000',
    dropdownItemTextColor: '#000',
    highlightColor: '#f2f2f2',
    settingsScrennBGlight: '#fff',
    settingsScrennBGDark: '#22272B',
    caruselStorageLearnModeTextColor: '#fff',
    caruselStorageFeesItemBGColor: '#fff',
    tertiaryBorderColor: '#2F80ED',
  }